/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home({list}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>CinemaNext</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Filmes em Destaque
        </h1>

        <Link href={'/busca'}>Ir para busca</Link>
        <Link href={'/sobre'}>Sobre</Link>

        <ul>
          {list.map(item=>(
            <li key={item}>
              <a href={`/movie/${item.id}`}>
                <img src={`https://image.tmdb.org/t/p/original${item.poster_path}`} alt='poster' width={150} layout='fill' /> <br/>
                {item.title}
              </a>
            </li>
          ))}
        </ul>

      </main>

      <footer className={styles.footer}>
        Powered by CWRSdev
      </footer>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch("http://localhost:3000/api/trending")
  const json = await res.json()

  return {
    props: {
      list: json.list
    }
  }
}
