/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Sobre({author}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>CinemaNext</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Sobre
        </h1>

        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tempus lacinia leo non tempus. Fusce tristique mi sit amet orci aliquam commodo. Ut eleifend massa velit. Ut id sapien sit amet odio gravida ultricies at sed metus. Donec mattis id elit eget blandit. Fusce finibus sollicitudin elit, vitae congue metus ultrices a. Nunc mattis risus erat, ac euismod dui pulvinar pulvinar. Integer in pretium felis, ut facilisis quam. Donec et velit tempor, convallis tellus non, dignissim ex. Sed tristique et turpis ut ullamcorper. Aliquam ante nulla, faucibus ut nisl id, dignissim faucibus velit. Sed laoreet urna et quam feugiat tempor. Pellentesque eu diam blandit, facilisis leo lobortis, pellentesque dolor. Phasellus at feugiat lectus.</p>

        Autor: {author}

      </main>

      <footer className={styles.footer}>
        Powered by CWRSdev
      </footer>
    </div>
  )
}

export async function getStaticProps() {

  return {
    props: {
      author: 'Carlos Wagner'
    }
  }
}
